apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocker-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pocker-web
  template:
    metadata:
      labels:
        app: pocker-web
    spec:
      containers:
      - name: web
        image: pocker-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_SIGNALING_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: pocker-config
              key: NEXT_PUBLIC_SIGNALING_SERVER_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pocker-web-service
  namespace: default
spec:
  selector:
    app: pocker-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP 